version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: estivadores-mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
    networks:
      - estivadores-network
  
  mongo-express:
    image: mongo-express:latest
    container_name: estivadores-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - estivadores-network

volumes:
  mongodb_data:
    name: estivadores-mongodb-data

networks:
  estivadores-network:
    name: estivadores-network
    driver: bridge